[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs@5"

[functions]
  node_bundler = "esbuild"
  
[build.processing.forms]
  enabled = true
  skip_processing = false

