[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false

[build.processing.forms]
  enabled = true

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200